name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install fpm
        run: |
          sudo gem install --no-document fpm

      - name: Install dependencies
        run: sudo apt-get install -y build-essential

      - name: Log in to Buf registry
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: |
          cargo login --registry buf "Bearer $BUF_TOKEN"

      - name: Build project
        run: make release

      - name: Package project
        run: make deb
