name: release

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
  workflow_dispatch:
env:
  # Default minimum version of Go to support.
  DEFAULT_GO_VERSION: 1.19
  REGISTRY: ghcr.io
  GITHUB_PAGES_BRANCH: gh_pages

defaults:
  run:
    shell: bash

jobs:
  release-please:
    permissions:
      contents: write  # for google-github-actions/release-please-action to create release commit
      pull-requests: write  # for google-github-actions/release-please-action to create release PR
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    # Release-please creates a PR that tracks all changes
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main
  release-charts:
    needs: release-please
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.releases_created == 'true'
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.K8SGPT_BOT_TOKEN }}
          charts_dir: chart
          charts_url: https://charts.k8sgpt.ai
          owner: k8sgpt-ai
          repository: charts
          branch: main
          commit_username: k8sgpt-ai-bot
          commit_email: bot@noreply.k8sgpt.ai